<h1> <center> Khadim Hussain <center><h1>
<h1> <center> 19-CP-71 <center><h1>
<h1> <center> DIP LAB 01<center><h1>

<h3> Task 01<h3>

Python vs C++ 


1.   Python has fewer lines of code.	C++ tends to have long lines of code.
2.   Python is dynamically typed.	C++ is statically typed.
3.   Python Functions do not have restrictions on the type of the argument and the type of its return value.
In C++, the function can accept and return the type of value which is already defined.
4.   In Python, variables are accessible even outside the loop.	In C++, the scope of variables is limited within the loops.
5.   python has no need to define variables while C++ we define variables






<h3> Task 02<h3>

Write a Python program that will print numbers from 10 to 20
using for-loop.

In [ ]:
for i in range (10,21):
  print(i)

10
11
12
13
14
15
16
17
18
19
20


<h3> Task 03<h3>

Create a list of state names such as
states = [’Minnesota’,’Texas’,’New York’,’Utah’,’Hawaii’].
Add another entry ’California’ to the end of the list. Then,
print all the values of this list.


In [ ]:
states = ['Minnesota','Texas','NewYork','Utah','Hawaii']
print(states)
states.append('California')
print('Afert adding California',states)


['Minnesota', 'Texas', 'NewYork', 'Utah', 'Hawaii']
Afert adding California ['Minnesota', 'Texas', 'NewYork', 'Utah', 'Hawaii', 'California']


<h3> Task 04<h3>

Create a 2D list of size 3-by-3 with the following elements:
1; 2; 3|4; 5; 6|6; 7; 8

In [ ]:
import numpy as np
list_2D=np.array([[1,2,3],[4,5,6],[6,7,8]])
list_2D

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

<h3> Task 05<h3>

Why is it more convenient to arrange the various functions as
modules?

Ans: 

1). minimizes the risks of programming errors

2).we use only one line of code insted of writing whole function 


<h3> Task 06<h3>

It is easy to convert a list to a set and vice versa. For
example, a list mylist = [1; 1; 2; 3; 4; 4; 5] can be converted
to a set using the command newset = set(mylist). The set can
be converted back to a list using newlist = list(newset).

In [1]:
mylist = [1, 1, 2, 3, 4, 4, 5] 
print('mylist = ',mylist)

newset=set(mylist)
print('newset = ',newset)
newlist=list(newset)
print('newlist = ',newlist)

mylist =  [1, 1, 2, 3, 4, 4, 5]
newset =  {1, 2, 3, 4, 5}
newlist =  [1, 2, 3, 4, 5]


sets does allow a duplicate element while in lists there may be duplicate elements 

mylist has duplicate elements and when we convert it into set by set(mylist)there will be no duplicate elements and when we convert back to list there will be no repetation

<h3> Task 07<h3>

Create a numpy array of size 5-by-5 containing all random
values. Determine the transpose and inverse of this matrix.

In [ ]:
x = np.random.random((5,5))
print(x)
print('Tanspose \n',np.transpose(x))
from numpy.linalg import inv
print('inverse of x \n', inv(x))



[[0.42565639 0.32319752 0.86285701 0.55254871 0.22253457]
 [0.64557856 0.18384305 0.82354282 0.8938474  0.26037862]
 [0.38008438 0.33677377 0.33690837 0.47829675 0.35759718]
 [0.87513059 0.67745352 0.60049897 0.87003693 0.54811408]
 [0.7030648  0.78928718 0.08379387 0.04989317 0.02325987]]
Tanspose 
 [[0.42565639 0.64557856 0.38008438 0.87513059 0.7030648 ]
 [0.32319752 0.18384305 0.33677377 0.67745352 0.78928718]
 [0.86285701 0.82354282 0.33690837 0.60049897 0.08379387]
 [0.55254871 0.8938474  0.47829675 0.87003693 0.04989317]
 [0.22253457 0.26037862 0.35759718 0.54811408 0.02325987]]
inverse of x 
 [[  6.93088117 -12.14214712 -51.26817487  36.81524252  -9.73363514]
 [ -6.24791969  10.71328189  45.12908521 -32.41544785   9.8967994 ]
 [  4.62756184  -4.66677112 -15.25168432  10.42643384  -3.24941319]
 [-10.29271596  16.19241545  54.56470603 -39.58466235  11.13729529]
 [  7.92434667 -14.44479295 -43.82518016  34.51994852 -10.80980935]]


<h3> Task 08<h3>

. Consider the following Python code:
a = [1,2,3,4,2,3,5]
b = []
for i in a:
if i>2:
b.append(i)
print(b)
Rewrite the above code using list comprehension and reduce
the number of lines

In [ ]:
a = [1,2,3,4,2,3,5]
b = [i for i in a if i>2] 
b

[3, 4, 3, 5]